[deps]
FFMPEG_jll = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RateLimiter = "24b76ae0-009b-4410-993f-7a05b90d7239"
STFT = "58bb99bf-048b-48b7-93e7-1cbf3ee61509"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"
